version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: react-native-calendars
    versions:
    - 1.1129.0
    - 1.1194.0
    - 1.1209.0
    - 1.1222.0
    - 1.1230.0
    - 1.1247.0
    - 1.1248.0
    - 1.1249.0
    - 1.1250.0
    - 1.1254.0
    - 1.1255.0
    - 1.1258.0
  - dependency-name: node-html-parser
    versions:
    - 2.0.2
    - 2.1.0
    - 2.2.0
    - 2.2.1
    - 3.0.2
    - 3.0.3
    - 3.0.4
    - 3.1.0
    - 3.1.2
    - 3.1.3
    - 3.1.4
    - 3.1.5
    - 3.1.6
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: handlebars
    versions:
    - 4.7.6
